### ISSUE TITLE
Feature requests ...

### ISSUE THREAD

**Issue by Sopor** [rebexnet/RebexTinySftpServer#4]
- Minimize to notification area (systray)

- Bind interface to other interfaces than 0.0.0.0

- Button to reload config file

- Always on top

**Comment by lukas-m** [comment]
Thank you for your suggestions.

We decided to add support for the first three feature requests. I have created separate issues for them, it will be easier to discuss and monitor the progress. However, they will not be added in the next version probably, because we already have a schedule for it.

Can you please describe, which problem would "Always on top" feature solve for you? We do not see it much useful, but maybe we are missing some scenario.

**Comment by lukas-m** [comment]
We decided to add the "Always on Top". I have created separated issue for it.
I am closing this issue, since all the requested features have a separate issue created.
